version: '2'
services:
  grafana_graphite:
    build: .
    image: sammymax/graphite09-grafana42
    container_name: grafana-graphite
    ports:
      - '82:80'
      - '127.0.0.1:81:81'
      - '8125:8125/udp'
      - '8126:8126'
      - '2003:2003'
    volumes:
      - ./data/whisper:/opt/graphite/storage/whisper
      - ./data/grafana:/opt/grafana/data
      - ./log/graphite:/opt/graphite/storage/log
